In [2]:
import numpy as np
print(np.__version__)

1.18.1


In [3]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [5]:
np.ones((2,2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [6]:
ar[ar % 2 == 0]

array([0, 2, 4])

In [9]:
ar[ar % 2 == 0] = -1
ar

array([-1,  1, -1,  3, -1])

In [11]:
ar = np.arange(5)
re = np.where(ar % 2 == 0, -1, ar)
print(ar)
re

[0 1 2 3 4]


array([-1,  1, -1,  3, -1])

In [12]:
ar = np.arange(8)
ar.reshape(2, -1) 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
a = np.arange(8).reshape(2,-1)
b = np.repeat(1, 8).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
a = np.arange(8).reshape(2,-1)
b = np.repeat(1, 8).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 1, 1, 1, 1],
       [4, 5, 6, 7, 1, 1, 1, 1]])

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [21]:
a = np.array([2, 6, 1, 9, 10, 3, 34, 50])
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
ar = np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
ar = np.arange(9).reshape(3,3)
ar[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [24]:
ar = np.arange(9).reshape(3,3)
ar[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [25]:
ar = np.arange(9).reshape(3,3)
ar[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [26]:
ar = np.arange(9).reshape(3,3)
ar[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [28]:
ar = np.arange(9).reshape(3,3)
rn_ar = np.random.uniform(5,10, size=(5,3))
print(rn_ar)

[[8.39928027 6.76176825 8.85367085]
 [6.15035763 5.92304236 7.99528391]
 [8.86704893 5.95552348 6.58188823]
 [6.27919197 8.2919999  6.16044883]
 [5.31388527 9.34270031 7.7034423 ]]


In [29]:
rn_ar = np.random.random([8,4])
np.set_printoptions(precision=3)
rn_ar[:4]

array([[0.654, 0.412, 0.432, 0.23 ],
       [0.699, 0.984, 0.026, 0.394],
       [0.559, 0.124, 0.898, 0.818],
       [0.005, 0.833, 0.27 , 0.3  ]])

In [36]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])